
[theme]
primaryColor = "#f63366"
#backgroundColor = "#f8f8f8"
backgroundColor = "#f1f1f1"
secondaryBackgroundColor = "#fdfdfd"
#secondaryBackgroundColor = "#154360"
textColor = "#092635"
font = "sans serif"




[server]
enableStaticServing = true
enableXsrfProtection = false
enableCORS = false


